version: "3.9"
services:
  weston:
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    - source: /run/udev
      target: /run/udev
      type: bind
    cap_add:
    - CAP_SYS_TTY_CONFIG
    network_mode: host
    device_cgroup_rules:
    - c 4:0 rmw
    - c 4:1 rmw
    - c 4:7 rmw
    - c 13:* rmw
    - c 199:* rmw
    - c 226:* rmw
    image: torizon/weston-vivante:3
    environment:
    - ACCEPT_FSL_EULA=1
  ct-demo-app:
    image: dominicpoeschko/ct-demo-app:ct
    device_cgroup_rules:
    - c 4:0 rmw
    - c 4:7 rmw
    - c 13:* rmw
    - c 199:* rmw
    - c 226:* rmw
    volumes:
    - source: /tmp
      target: /tmp
      type: bind
    - source: /dev
      target: /dev
      type: bind
    depends_on:
    - weston
